### ISSUE TITLE
Contact for autorization to use in a mod

### ISSUE THREAD

**Issue by Not-Erik** [BlueWinds/WarTechIIC#5]
Hello!

I'm developing a branch of your mod to be compatible with another mod, and I have a few questions:

What do I need to do in order to do it? Add your name incredits, add a license file, etc etc etc

Can I upload on nexus (if possible/avaliable)? If not, were I'm autorized to post the mod?

Thank you very much for your amazing mod! It was surprisingly easy to use and well coded.

**Comment by BlueWinds** [comment]
WIIC is GPL-3.0 licensed: https://github.com/BlueWinds/WarTechIIC/blob/master/LICENSE

Your fork must use the same license  (GPL 3.0, granting all these same rights to everyone else), and give credit to the original; you also *must* provide your users with access to the source code in addition to the complied dlls.

Other than that, go wild! :) You can upload and share wherever and however you like, as long as you use the same GPL license and make the source available!

If you wanted to contribute back so that everyone can benefit from your changes, I'd encourage that as well, but not a requirement.

**Comment by Not-Erik** [comment]
Ok! Thank you very much! As soon as I finish the mod I will be adding a version here in git too.
